# Generated by Django 3.1.6 on 2021-03-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0005_auto_20210310_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='importanceLevel',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, null=True),
        ),
    ]
