# Generated by Django 3.1.6 on 2021-03-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0009_auto_20210325_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
