# Generated by Django 3.1.6 on 2021-03-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_remove_todoitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
