# Generated by Django 3.1.6 on 2021-04-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0014_auto_20210407_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
